wandb_version: 1

learning_rate:
  desc: null
  value: 0.04
architecture:
  desc: null
  value: BERT
dataset:
  desc: null
  value: plantbert
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697793093.008449
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.15.12
      6: 4.34.0
      8:
      - 5
      13: linux-x86_64
